/**
 * RoomPlanr - Architectural Furniture & Fixtures Catalog
 * 40+ architectural items with real-world dimensions, CAD 2D rendering hints, materials, and pricing.
 */

export const FURNITURE_CATALOG = [
  // --- Living / Sofas & Seating ---
  {
    type: 'sofa_3seat',
    name: '3-Seater Tailored Sofa',
    category: 'Living',
    width: 2.20,
    depth: 0.95,
    height: 0.85,
    color: '#3b4252',
    material: 'Belgian Bouclé Charcoal',
    price: 2450,
    sku: 'SOF-3S-CHR',
    icon: 'sofa'
  },
  {
    type: 'sofa_lshape',
    name: 'L-Sectional Chaise Sofa',
    category: 'Living',
    width: 2.80,
    depth: 1.80,
    height: 0.85,
    color: '#2e3440',
    material: 'Performance Slate Linen',
    price: 3850,
    sku: 'SOF-SEC-SLT',
    icon: 'sofa'
  },
  {
    type: 'armchair',
    name: 'Mid-Century Lounge Armchair',
    category: 'Living',
    width: 0.85,
    depth: 0.85,
    height: 0.80,
    color: '#0284c7',
    material: 'Cognac Saddle Leather',
    price: 1250,
    sku: 'ARM-MC-CGN',
    icon: 'chair'
  },
  {
    type: 'club_chair',
    name: 'Sculptural Club Chair',
    category: 'Living',
    width: 0.90,
    depth: 0.85,
    height: 0.78,
    color: '#0f766e',
    material: 'Forest Green Mohair',
    price: 980,
    sku: 'CHR-CLB-FST',
    icon: 'chair'
  },
  {
    type: 'coffee_table',
    name: 'Solid Walnut Coffee Table',
    category: 'Living',
    width: 1.30,
    depth: 0.65,
    height: 0.42,
    color: '#78350f',
    material: 'Solid American Walnut',
    price: 850,
    sku: 'TBL-COF-WAL',
    icon: 'table'
  },
  {
    type: 'tv_unit',
    name: 'Lowline Media Credenza',
    category: 'Living',
    width: 2.00,
    depth: 0.45,
    height: 0.50,
    color: '#1e293b',
    material: 'Matte Obsidian Ash',
    price: 1400,
    sku: 'CRD-MED-OBS',
    icon: 'table'
  },
  {
    type: 'rug_large',
    name: 'Large Hand-Tufted Area Rug',
    category: 'Living',
    width: 3.00,
    depth: 2.00,
    height: 0.02,
    color: '#cbd5e1',
    material: 'Organic New Zealand Wool',
    price: 1150,
    sku: 'RUG-WOOL-NZ',
    icon: 'room'
  },
  {
    type: 'side_table',
    name: 'Fluted Pedestal Side Table',
    category: 'Living',
    width: 0.50,
    depth: 0.50,
    height: 0.55,
    color: '#d97706',
    material: 'Honed Roman Travertine',
    price: 420,
    sku: 'TBL-SIDE-TRV',
    icon: 'table'
  },

  // --- Bedroom / Beds & Storage ---
  {
    type: 'bed_king',
    name: 'King Size Platform Bed',
    category: 'Bedroom',
    width: 2.05,
    depth: 2.15,
    height: 1.10,
    color: '#475569',
    material: 'Upholstered Warm Sand',
    price: 2800,
    sku: 'BED-KNG-SND',
    icon: 'bed'
  },
  {
    type: 'bed_queen',
    name: 'Queen Size Upholstered Bed',
    category: 'Bedroom',
    width: 1.65,
    depth: 2.10,
    height: 1.05,
    color: '#334155',
    material: 'Heather Gray Wool Blend',
    price: 2200,
    sku: 'BED-QEN-HGR',
    icon: 'bed'
  },
  {
    type: 'bed_single',
    name: 'Single Twin Daybed',
    category: 'Bedroom',
    width: 1.05,
    depth: 2.00,
    height: 0.85,
    color: '#0369a1',
    material: 'Washed Indigo Linen',
    price: 1150,
    sku: 'BED-TWN-IND',
    icon: 'bed'
  },
  {
    type: 'nightstand',
    name: 'Bedside Nightstand',
    category: 'Bedroom',
    width: 0.55,
    depth: 0.45,
    height: 0.55,
    color: '#b45309',
    material: 'Solid French Oak',
    price: 450,
    sku: 'STN-BED-OAK',
    icon: 'table'
  },
  {
    type: 'wardrobe',
    name: 'Double Wardrobe Armoire',
    category: 'Bedroom',
    width: 1.80,
    depth: 0.60,
    height: 2.20,
    color: '#1e293b',
    material: 'Matte Charcoal & Satin Brass',
    price: 2600,
    sku: 'WRD-ARM-MAT',
    icon: 'room'
  },
  {
    type: 'dresser',
    name: '6-Drawer Low Dresser',
    category: 'Bedroom',
    width: 1.60,
    depth: 0.50,
    height: 0.85,
    color: '#78350f',
    material: 'Smoked Walnut Finish',
    price: 1850,
    sku: 'DRS-6DR-WAL',
    icon: 'table'
  },
  {
    type: 'mirror_full',
    name: 'Full-Length Floor Mirror',
    category: 'Bedroom',
    width: 0.70,
    depth: 0.15,
    height: 1.90,
    color: '#64748b',
    material: 'Bronzed Aluminum Frame',
    price: 620,
    sku: 'MIR-FLR-BRZ',
    icon: 'window'
  },

  // --- Work / Office ---
  {
    type: 'desk_exec',
    name: 'Executive Workstation Desk',
    category: 'Office',
    width: 1.80,
    depth: 0.85,
    height: 0.75,
    color: '#78350f',
    material: 'Solid American Walnut',
    price: 2100,
    sku: 'DSK-EXC-WAL',
    icon: 'desk'
  },
  {
    type: 'desk_standing',
    name: 'Motorized Sit-Stand Desk',
    category: 'Office',
    width: 1.50,
    depth: 0.75,
    height: 0.75,
    color: '#0f172a',
    material: 'White Oak & Matte Steel',
    price: 1350,
    sku: 'DSK-STD-MTR',
    icon: 'desk'
  },
  {
    type: 'office_chair',
    name: 'Ergonomic Task Chair',
    category: 'Office',
    width: 0.68,
    depth: 0.68,
    height: 1.10,
    color: '#0284c7',
    material: 'High-Tensile Ergonomic Mesh',
    price: 890,
    sku: 'CHR-TSK-MSH',
    icon: 'chair'
  },
  {
    type: 'bookshelf',
    name: 'Tall Architectural Bookshelf',
    category: 'Office',
    width: 1.20,
    depth: 0.35,
    height: 2.00,
    color: '#334155',
    material: 'Powdercoated Steel & Oak',
    price: 1200,
    sku: 'SHF-BOK-STL',
    icon: 'room'
  },
  {
    type: 'file_cabinet',
    name: '2-Drawer Mobile Pedestal',
    category: 'Office',
    width: 0.42,
    depth: 0.52,
    height: 0.60,
    color: '#475569',
    material: 'Architectural Steel Gray',
    price: 380,
    sku: 'CAB-MOB-GRY',
    icon: 'table'
  },

  // --- Dining & Kitchen ---
  {
    type: 'dining_table_6',
    name: '6-Person Rectangular Dining Table',
    category: 'Dining',
    width: 1.90,
    depth: 0.95,
    height: 0.76,
    color: '#b45309',
    material: 'Solid European White Oak',
    price: 1950,
    sku: 'TBL-DIN-6P',
    icon: 'table'
  },
  {
    type: 'dining_table_round',
    name: 'Round Dining Table (4-Seat)',
    category: 'Dining',
    width: 1.20,
    depth: 1.20,
    height: 0.76,
    color: '#e2e8f0',
    material: 'Italian Carrara Marble',
    price: 2300,
    sku: 'TBL-RND-MAR',
    icon: 'table'
  },
  {
    type: 'dining_chair',
    name: 'Molded Dining Chair',
    category: 'Dining',
    width: 0.52,
    depth: 0.52,
    height: 0.82,
    color: '#475569',
    material: 'Molded Oak & Wool Seat',
    price: 360,
    sku: 'CHR-DIN-MLD',
    icon: 'chair'
  },
  {
    type: 'kitchen_island',
    name: 'Waterfall Quartz Kitchen Island',
    category: 'Kitchen',
    width: 2.20,
    depth: 0.95,
    height: 0.92,
    color: '#1e293b',
    material: 'Calacatta Gold Quartz',
    price: 4500,
    sku: 'ISL-KIT-QRT',
    icon: 'table'
  },
  {
    type: 'fridge',
    name: 'French Door Integrated Refrigerator',
    category: 'Kitchen',
    width: 0.92,
    depth: 0.75,
    height: 1.90,
    color: '#94a3b8',
    material: 'Brushed Stainless Steel',
    price: 3200,
    sku: 'APP-FRG-SS',
    icon: 'room'
  },
  {
    type: 'stove_oven',
    name: 'Induction Range & Convection Oven',
    category: 'Kitchen',
    width: 0.76,
    depth: 0.65,
    height: 0.90,
    color: '#0f172a',
    material: 'Matte Cast Iron & Ceramic Glass',
    price: 2400,
    sku: 'APP-STV-IND',
    icon: 'room'
  },
  {
    type: 'bar_stool',
    name: 'Counter Bar Stool',
    category: 'Dining',
    width: 0.45,
    depth: 0.45,
    height: 0.95,
    color: '#78350f',
    material: 'Walnut & Saddle Leather',
    price: 320,
    sku: 'STL-BAR-WAL',
    icon: 'chair'
  },

  // --- Bathroom Fixtures ---
  {
    type: 'bath_tub',
    name: 'Freestanding Oval Soaking Tub',
    category: 'Bathroom',
    width: 1.70,
    depth: 0.80,
    height: 0.60,
    color: '#f8fafc',
    material: 'Matte Solid Surface Resin',
    price: 2900,
    sku: 'BAT-OVL-RES',
    icon: 'bath'
  },
  {
    type: 'vanity_double',
    name: 'Double Basin Vanity Counter',
    category: 'Bathroom',
    width: 1.50,
    depth: 0.55,
    height: 0.85,
    color: '#b45309',
    material: 'Fluted Oak & Quartz Top',
    price: 2400,
    sku: 'VAN-DBL-OAK',
    icon: 'table'
  },
  {
    type: 'shower_enclosure',
    name: 'Walk-In Frameless Glass Shower',
    category: 'Bathroom',
    width: 1.20,
    depth: 0.90,
    height: 2.10,
    color: '#38bdf8',
    material: 'Tempered Glass & Brass Trim',
    price: 1800,
    sku: 'SHW-WKI-GLS',
    icon: 'bath'
  },
  {
    type: 'toilet',
    name: 'Wall-Hung Ceramic Toilet',
    category: 'Bathroom',
    width: 0.40,
    depth: 0.60,
    height: 0.45,
    color: '#f8fafc',
    material: 'Glazed Alpine White Porcelain',
    price: 750,
    sku: 'SAN-TOI-POR',
    icon: 'bath'
  },

  // --- Lighting & Decor ---
  {
    type: 'floor_lamp',
    name: 'Arched Brass Floor Lamp',
    category: 'Decor',
    width: 0.50,
    depth: 0.50,
    height: 1.85,
    color: '#d97706',
    material: 'Spun Brass & Natural Linen',
    price: 580,
    sku: 'LMP-ARC-BRS',
    icon: 'lamp'
  },
  {
    type: 'plant_monstera',
    name: 'Potted Monstera Deliciosa',
    category: 'Decor',
    width: 0.55,
    depth: 0.55,
    height: 1.00,
    color: '#15803d',
    material: 'Terracotta Vessel & Flora',
    price: 160,
    sku: 'DEC-PLT-MON',
    icon: 'plant'
  },
  {
    type: 'plant_fiddle',
    name: 'Architectural Fiddle Leaf Fig',
    category: 'Decor',
    width: 0.65,
    depth: 0.65,
    height: 1.75,
    color: '#166534',
    material: 'Fluted Ceramic Planter',
    price: 240,
    sku: 'DEC-PLT-FID',
    icon: 'plant'
  },
  {
    type: 'plant_olive',
    name: 'Large Potted Olive Tree',
    category: 'Decor',
    width: 0.75,
    depth: 0.75,
    height: 1.95,
    color: '#14532d',
    material: 'Aged Stone Urn Planter',
    price: 350,
    sku: 'DEC-PLT-OLV',
    icon: 'plant'
  },

  // --- Structural Openings & Columns ---
  {
    type: 'door_standard',
    name: 'Single Interior Swing Door',
    category: 'Structure',
    width: 0.90,
    depth: 0.15,
    height: 2.10,
    color: '#cbd5e1',
    material: 'Solid Core Painted Wood',
    price: 450,
    sku: 'STR-DOR-SGL',
    icon: 'door',
    isDoor: true
  },
  {
    type: 'door_double',
    name: 'Double French Swing Doors',
    category: 'Structure',
    width: 1.60,
    depth: 0.15,
    height: 2.10,
    color: '#94a3b8',
    material: 'Glazed Timber Frame',
    price: 950,
    sku: 'STR-DOR-DBL',
    icon: 'door',
    isDoor: true
  },
  {
    type: 'window_standard',
    name: 'Casement Picture Window',
    category: 'Structure',
    width: 1.40,
    depth: 0.20,
    height: 1.50,
    color: '#38bdf8',
    material: 'Low-E Double Glazed Glass',
    price: 850,
    sku: 'STR-WIN-CSM',
    icon: 'window',
    isWindow: true
  },
  {
    type: 'window_large',
    name: 'Panoramic Floor-to-Ceiling Glazing',
    category: 'Structure',
    width: 2.40,
    depth: 0.20,
    height: 2.40,
    color: '#0284c7',
    material: 'Thermally Broken Aluminum',
    price: 2100,
    sku: 'STR-WIN-PAN',
    icon: 'window',
    isWindow: true
  },
  {
    type: 'column_sq',
    name: 'Square Structural Column',
    category: 'Structure',
    width: 0.40,
    depth: 0.40,
    height: 2.80,
    color: '#475569',
    material: 'Reinforced Architectural Concrete',
    price: 600,
    sku: 'STR-COL-SQ',
    icon: 'room'
  }
];

export const FLOOR_MATERIALS = {
  oak: {
    id: 'oak',
    name: 'European White Oak Plank',
    color: '#c4975e',
    stroke: '#a37843',
    tile: false,
    costPerSqM: 110
  },
  walnut: {
    id: 'walnut',
    name: 'Smoked Walnut Chevron',
    color: '#593822',
    stroke: '#402615',
    tile: false,
    costPerSqM: 145
  },
  marble: {
    id: 'marble',
    name: 'Italian Carrara Marble',
    color: '#e2e8f0',
    stroke: '#cbd5e1',
    tile: true,
    costPerSqM: 190
  },
  concrete: {
    id: 'concrete',
    name: 'Polished Architectural Screed',
    color: '#64748b',
    stroke: '#475569',
    tile: false,
    costPerSqM: 85
  },
  terrazzo: {
    id: 'terrazzo',
    name: 'Venetian Terrazzo Grigio',
    color: '#cbd5e1',
    stroke: '#94a3b8',
    tile: true,
    costPerSqM: 160
  },
  carpet: {
    id: 'carpet',
    name: 'Charcoal Berber Plush',
    color: '#334155',
    stroke: '#1e293b',
    tile: false,
    costPerSqM: 70
  }
};
